### ISSUE TITLE
启动报错：one-api  | main.main() one-api  | 	github.com/songquanpeng/one-api/main.go:106 +0x934

### ISSUE THREAD

**Issue by Caixiaopig** [Laisky/one-api#16]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用 docker image `ppcelery/one-api:latest`，启动报错
`one-api  | main.main() one-api  | 	github.com/songquanpeng/one-api/main.go:106 +0x934`

**复现步骤**
docker compose up

**预期结果**
正常启动

**相关截图**
如果没有的话，请删除此节。

**Comment by Laisky** [comment]
是因为我对 SESSION SECRET 加了个非兼容的变更导致的（我要求必须设置为 base64）。

新版（IMAGE ID `d5e56e469cb6`）已经修复了，可以再试试。如果还有问题，请 reopen 这个 issue。
