### ISSUE TITLE
增加arm64 docker镜像

### ISSUE THREAD

**Issue by jinjunliu** [Laisky/one-api#17]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
开发者你好，请问可以增加linux/arm64的docker镜像吗？

**应用场景**
用于在Linux arm64机器上部署该应用。

**Comment by Laisky** [comment]
@jinjunliu 你试试 `ppcelery/one-api:arm64-5812cb3` 能用吗？

如果可以的话，我之后每次更新会同步更新 `ppcelery/one-api:arm64-latest`

**Comment by jinjunliu** [comment]
可以用，感恩！
![image](https://github.com/user-attachments/assets/f0e40428-b1e5-41b7-8de8-0f91733142f5)

**Comment by Laisky** [comment]
@jinjunliu 没问题的话可以把镜像 tag 更换为 `arm64-latest`，以后就更新这个 tag 了。
